/**
 * GitHub Integration Service
 * 
 * Syncs focus sessions, tasks, and productivity data with GitHub:
 * - Create issues from tasks
 * - Track commits during focus sessions
 * - Generate productivity reports as gists
 * - Update project boards
 * - Sync with GitHub Projects
 */

import { Octokit } from '@octokit/rest';

export interface GitHubConfig {
  accessToken: string;
  owner: string;
  repo: string;
}

export interface GitHubTask {
  title: string;
  description?: string;
  labels?: string[];
  assignees?: string[];
  milestone?: number;
}

export interface GitHubCommit {
  sha: string;
  message: string;
  author: string;
  date: Date;
  url: string;
}

export class GitHubIntegration {
  private octokit: Octokit;
  private owner: string;
  private repo: string;

  constructor(config: GitHubConfig) {
    this.octokit = new Octokit({
      auth: config.accessToken,
    });
    this.owner = config.owner;
    this.repo = config.repo;
  }

  /**
   * Create GitHub issue from task
   */
  async createIssue(task: GitHubTask): Promise<{ number: number; url: string }> {
    const response = await this.octokit.issues.create({
      owner: this.owner,
      repo: this.repo,
      title: task.title,
      body: task.description,
      labels: task.labels,
      assignees: task.assignees,
      milestone: task.milestone,
    });

    return {
      number: response.data.number,
      url: response.data.html_url,
    };
  }

  /**
   * Get commits during a time range (focus session)
   */
  async getCommitsDuringSession(
    startTime: Date,
    endTime: Date
  ): Promise<GitHubCommit[]> {
    const response = await this.octokit.repos.listCommits({
      owner: this.owner,
      repo: this.repo,
      since: startTime.toISOString(),
      until: endTime.toISOString(),
    });

    return response.data.map((commit) => ({
      sha: commit.sha,
      message: commit.commit.message,
      author: commit.commit.author?.name || 'Unknown',
      date: new Date(commit.commit.author?.date || Date.now()),
      url: commit.html_url,
    }));
  }

  /**
   * Create productivity report as gist
   */
  async createProductivityReport(data: {
    date: string;
    focusHours: number;
    tasksCompleted: number;
    productivity: number;
    commits: number;
    topApps: { name: string; time: number }[];
  }): Promise<string> {
    const content = `# Productivity Report - ${data.date}

## Summary
- 🎯 Focus Hours: ${data.focusHours}h
- ✅ Tasks Completed: ${data.tasksCompleted}
- 📊 Productivity Score: ${data.productivity}%
- 💻 Commits: ${data.commits}

## Top Applications
${data.topApps.map((app, i) => `${i + 1}. ${app.name} - ${app.time}min`).join('\n')}

---
Generated by Forgrin
`;

    const response = await this.octokit.gists.create({
      description: `Productivity Report - ${data.date}`,
      public: false,
      files: {
        [`productivity-${data.date}.md`]: {
          content,
        },
      },
    });

    return response.data.html_url;
  }

  /**
   * Update issue status when task is completed
   */
  async updateIssueStatus(
    issueNumber: number,
    status: 'open' | 'closed',
    comment?: string
  ): Promise<void> {
    await this.octokit.issues.update({
      owner: this.owner,
      repo: this.repo,
      issue_number: issueNumber,
      state: status,
    });

    if (comment) {
      await this.octokit.issues.createComment({
        owner: this.owner,
        repo: this.repo,
        issue_number: issueNumber,
        body: comment,
      });
    }
  }

  /**
   * Get repository statistics
   */
  async getRepoStats(): Promise<{
    stars: number;
    forks: number;
    openIssues: number;
    watchers: number;
  }> {
    const response = await this.octokit.repos.get({
      owner: this.owner,
      repo: this.repo,
    });

    return {
      stars: response.data.stargazers_count,
      forks: response.data.forks_count,
      openIssues: response.data.open_issues_count,
      watchers: response.data.watchers_count,
    };
  }

  /**
   * Get user's contribution activity
   */
  async getUserActivity(username: string): Promise<{
    totalCommits: number;
    totalPRs: number;
    totalIssues: number;
  }> {
    const [commits, prs, issues] = await Promise.all([
      this.octokit.search.commits({
        q: `author:${username} repo:${this.owner}/${this.repo}`,
      }),
      this.octokit.search.issuesAndPullRequests({
        q: `author:${username} repo:${this.owner}/${this.repo} type:pr`,
      }),
      this.octokit.search.issuesAndPullRequests({
        q: `author:${username} repo:${this.owner}/${this.repo} type:issue`,
      }),
    ]);

    return {
      totalCommits: commits.data.total_count,
      totalPRs: prs.data.total_count,
      totalIssues: issues.data.total_count,
    };
  }

  /**
   * Create project card for task
   */
  async addToProject(
    projectId: number,
    columnId: number,
    contentId: number,
    contentType: 'Issue' | 'PullRequest'
  ): Promise<void> {
    await this.octokit.projects.createCard({
      column_id: columnId,
      content_id: contentId,
      content_type: contentType,
    });
  }
}

/**
 * Helper function to initialize GitHub integration
 */
export function createGitHubIntegration(
  accessToken: string,
  owner: string,
  repo: string
): GitHubIntegration {
  return new GitHubIntegration({ accessToken, owner, repo });
}
